### ISSUE TITLE
Demonstration Video

### ISSUE THREAD

**Issue by bjadamson** [mbillingr/ambisonic#10]
I made a [video](https://www.youtube.com/watch?v=LrLn5t2zEp4) demonstrating how Ambisonic is able to work in a 3D game I'd like to share with you. I thought maybe it could be useful for promoting the library with a real-world example.

Feel free to close. 
:)

**Comment by mbillingr** [comment]
Nice! I'll have to watch this at home, though :)

**Comment by mbillingr** [comment]
Very cool. With graphics the spatial audio is much more tangible than with the little examples I made.

In ambisonic the default coordinate system is z up and y into the screen, while in 3D graphics it's usually the other way round. Did that cause you any trouble?

Do you mind if I put a link to the video in the readme?

**Comment by bjadamson** [comment]
> In ambisonic the default coordinate system is z up and y into the screen, while in 3D graphics it's usually the other way round. Did that cause you any trouble?

Huh. No, no it didn't but I didn't do anything to compensate for it. Do you know much about 3D graphics? I multiplied the camera's position in local space (0,0,0) by the model-view-projection matrix for each model to calculate a position in local space for each audio source. From what I've learned about ambisonic is that the audio system is in local space as well w/regards to the listener. Is this correct?

If so, I may either be doing something wrong w/regards to not handling the different coordinate systems or it doesn't matter for my use case (at least yet) for some reason I don't understand yet.

> Do you mind if I put a link to the video in the readme?

Nope not at all.

**Comment by mbillingr** [comment]
> From what I've learned about ambisonic is that the audio system is in local space as well w/regards to the listener. Is this correct?

Yes, this is correct.
In ambisonic's default configuration the *y*-coordinate points forward. As far I know, the OpenGL convention is tha *z* coordinate points forward (into the screen) and *y* points up, not sure about DirectX and other standards. 

I think you can find out if you have a coordinate system mismatch. The sound should be loudest if you look straight at a source. If it gets louder when looking up or down, something is not right.

**Comment by bjadamson** [comment]
I've been working on this for a few days, the coordinate system seems like a match so far. Thanks for letting me know this.

**Comment by mbillingr** [comment]
The video is now linked from the readme. Thanks again!

Since no coordinate-related problems seem to have popped up I'll close this thread for now. Feel free to reopen.
