### ISSUE TITLE
HRTF causes underrun in ALSA

### ISSUE THREAD

**Issue by porky11** [mbillingr/ambisonic#13]
I tried to run the examples, which use HRTF, and I always get this error:

```
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
```
 Not sure, if that's a bug in ambisonic or if I have to change my system settings.

**Comment by mbillingr** [comment]
Thank you for reporting this issue!

My first guess is that ambisonic did not deliver sound samples fast enough. The HRTF backend is computationally rather demanding and not very optimized yet...

Did you compile the example in Release mode?

**Comment by porky11** [comment]
Looks like I just didn't have `alsa-plugins-pulseaudio` installed. It only worked after reboot.
