### ISSUE TITLE
Questions about loading an mp3/wav from rodio

### ISSUE THREAD

**Issue by bjadamson** [mbillingr/ambisonic#5]
Hello there, thanks for making this project! I went about trying to figure out how to an mp3 I loaded using the rodio library, and wanted to share what I found and discuss with you what you think. I hope that is ok!

First my use case is for a game I am making, whenever an NPC is moving I want to play a walking/running/slithering/buzzing/etc... sound at their 3d location. Before finding your library, I got this working using rodio, but my plan was to have your library help me with the 3d part of it. Without the 3d part the game doesn't feel as immersive.

My code is setup to hold a buffer of the data so I can create a sink when I want to play it, or pause it when the NPC stops moving.

I tried copy/pasting the code from the ambisonic readme and swapping the source to the source containing my mp3 file, but I got an error about a type-mismatch:
![image](https://user-images.githubusercontent.com/1087837/107217064-80c68d80-69c2-11eb-93b4-c1521220d548.png)

To work around this I figured out this adaptor code:

```rust
/// Since rodio requires everything to be Send + Sync, the data is wrapped with Arc so only one copy
/// of the data is in memory at a time per-sound.
#[derive(Default)]
pub struct Sound(Arc<Vec<u8>>);
impl AsRef<[u8]> for Sound {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

impl Sound {
    pub fn cursor(self: &Self) -> Cursor<Sound> {
        Cursor::new(Sound(self.0.clone()))
    }
}
```

This wrapper type wraps my custom buffer:
```rust
struct Wrapper(ambisonic::rodio::Decoder<Cursor<Sound>>);

impl Iterator for Wrapper {
    type Item = f32;

    #[inline]
    fn next(&mut self) -> Option<f32> {
        self.0.next().map(|v| v as f32) // v is type i16, is mapping the i16 value to f32 valid?
    }
}

impl ambisonic::rodio::Source for Wrapper {
    #[inline]
    fn current_frame_len(&self) -> Option<usize> {
        self.0.current_frame_len()
    }

    #[inline]
    fn channels(&self) -> u16 {
        self.0.channels()
    }

    #[inline]
    fn sample_rate(&self) -> u32 {
        self.0.sample_rate()
    }

    #[inline]
    fn total_duration(&self) -> Option<Duration> {
        self.0.total_duration()
    }
}
```

Also I needed to wrap the source:
```rust
let source = ambisonic::rodio::Decoder::new(cursor).unwrap();
let source = Wrapper(source); // wrap
let mut sound = scene.play_at(source, pos);
```

This `Wrapper` gets the code to compile and executing it works, the mp3 sound plays left-to-right in my headphones just like the sine wave code from the readme.

1. All this boilerplate boils down to implementing `Iterator` for the type passed into `play_at()` because play_at() expects the input value to implement it for f32. Can ambisonic be changed to not care, or is f32 important here? Is mapping the i16 value to f32 valid?
2. Since I was already using rodio in my project, I kept running into conflicts. Is it possible to disable exposing the rodio version used by ambisonic internally? This way I can keep using rodio from my cargo.toml and ambisonic can use the version it wants internally?

I'm super impressed that with such a small change ambisonic was able to work with the mp3 file, congrats on building something so cool (:

**Comment by mbillingr** [comment]
Hi! It's cool that you want to use ambisonic in an actual game. I never really started writing the game I wanted to use it in, so I hardly know how practical the API is... in other words: any feedback is highly appreciated :)

1. `i16` to `f32` is a lossless conversion and should be no problem. There is a subtle scaling issue, though: `f32` audio samples are usually in the range `-1...1` while the simple cast results in a range of `-32768...32767`. Since you heard the sound just fine there does not seem to be a problem, though. I agree that this is a pain point in the API that should be improved.

2. I'm not sure if it is possible to use different versions of Rodio simultaneously and it may be hard to completely decouple ambisonic from Rodio, but there is certainly room for improvement. Can you point me to some specific conflicts you have had?

**Comment by bjadamson** [comment]
> 1. i16 to f32 is a lossless conversion and should be no problem. There is a subtle scaling issue, though: f32 audio samples are usually in the range -1...1 while the simple cast results in a range of -32768...32767. Since you heard the sound just fine there does not seem to be a problem, though. I agree that this is a pain point in the API that should be improved.

Well I don't want to claim the audio sounds correct by any means I only started using ambisonic today. I got it to play and I was obviously excited. Right now I'm still trying to figure out how to adjust the audio level for the sounds. The audio is really loud unless I set the position's z value to something like 50000. So I don't know if I'm using the API incorrect or the casted value is somehow messing with the audio. However after reading your response I [printed ](https://gist.github.com/bjadamson/44309c8922c3a4d56bf5955d720f0fdd)the i16 values out just to see what they were. After looking at the printed values I tried dividing the sample values by 255 and 128 (thinking I could get them into the range [-1..1]) which significantly reduced the volume, but I'm not sure what actually needs to be done here. I think I'm on the right track, but I don't think directly modifying the sample values is the correct way to adjust the volume.

> 2. I'm not sure if it is possible to use different versions of Rodio simultaneously and it may be hard to completely decouple ambisonic from Rodio, but there is certainly room for improvement. Can you point me to some specific conflicts you have had?

Sure thing. My project was already using rodio, and to use ambisonic the example code demonstrates pulling in the ambisonic::rodio module. Invoking the `play_at` function with a source that implements the 'rodio' instead of the 'ambisonic::rodio' trait (like my wrapper struct) causes a compilation error.

ie:
```rust
// changing
impl ambisonic::rodio::Source for Wrapper {

// to this
impl rodio::Source for Wrapper {
```
![image](https://user-images.githubusercontent.com/1087837/107262260-2c88d100-69f5-11eb-94cd-2c4286ca697c.png)

**Comment by mbillingr** [comment]
1. I typically work with sample values in ranges not much larger than -1..1, and place the sources much closer to the center... say 100 or less. I think the correct approach for the conversion is to do `|v| v as f32 / i16::MAX as f32`. Then you can use a lower value for z (between 1 and 10 should be a good start).

2. If you are using a recent version of rodio (0.12 or 0.13) this would explain the problem. Ambisonic only supports rodio up to 0.11 at the moment. I'm working on the necessary fixes now, so the next release will work with the most current rodio version.

**Comment by mbillingr** [comment]
1. There is actually an easier way to convert audio samples. Rodio sources have a [`.convert_samples()`](https://docs.rs/rodio/0.13.0/rodio/source/trait.Source.html#method.convert_samples) method for this purpose. The following worked for me:
```rust
let file = std::fs::File::open("../../Downloads/Engine_01.wav").unwrap();
let source = rodio::Decoder::new(std::io::BufReader::new(file)).unwrap();
let source = source.repeat_infinite();

let mut sound = scene.play_at(source.convert_samples(), [50.0, 1.0, 0.0]);
```

**Comment by bjadamson** [comment]
That's amazing, and it just works. Thanks!

I think the code you posted above would go along way in helping someone else in the future. Would you be interested in a PR that adds your example to the documentation?

**Comment by mbillingr** [comment]
Sure! Go ahead :)
Maybe you can think of a nice generic replacement for the audio file name? Others obviously won't have that file available...

**Comment by mbillingr** [comment]
By the way, does version 4.0 correctly work with your rodio?

**Comment by bjadamson** [comment]
Yes it does I upgraded this morning, and was able to remove all references to `ambisonic::rodio` and just use `rodio`, everything worked nicely. Thanks for updating!
