### ISSUE TITLE
How to restart stream after pause/stop?

### ISSUE THREAD

**Issue by bjadamson** [mbillingr/ambisonic#8]
Hi again, since you requested feedback I wanted to create another issue for this question. Is it possible to pause a stream? I don't see this in the [SoundController](https://github.com/mbillingr/ambisonic/blob/b7a898fcc848152dfde2080c3e482d101dcaa844/src/bstream.rs#L220-L291):
```rust
pub fn stop(&self);
pub fn set_doppler_factor(&mut self, factor: f32);
pub fn set_velocity(&mut self, vel: [f32; 3]);
pub fn adjust_position(&mut self, pos: [f32; 3]);
pub fn set_position(&mut self, pos: [f32; 3]);
```

In rodio stop() drops all the bytes from the stream, and playing again after a stream isn't possible it seems. Pausing a stream does work for me using rodio. It is possible to allow me to pause the sound using the SoundController and then play it again in ambisonic?

**Comment by mbillingr** [comment]
This functionality is missing indeed.

A naive implementation could simply produce 0-valued samples while the stream is paused, but then paused streams would still consume CPU time.
I'll need to think about this a bit. Maybe there is a way to do this without performance penalty...

**Comment by bjadamson** [comment]
I could be wrong, but I think that's what [rodio does](https://github.com/RustAudio/rodio/blob/e1aea73ba0f7c93a4b38dfe5bf05f2337badfe21/src/source/pausable.rs#L75-L84).

edit: I'm not saying that's good.. just thinking outloud

**Comment by mbillingr** [comment]
Right... but rodio also supports pausing at the sink level.
Also, the 3d sources are more expensive to play.
